### ISSUE TITLE
This repo is for cool kids only

### ISSUE THREAD

**Issue by mjgerace** [seanpwhitehurst/seanwhitehurst-web#2]
Hello Sheen,

I was wondering if it were possible to open this repo up to more contributors. Currently, you aren't accepting PRs from anyone who is not a 'cool kid'. But I think that this repo could benefit from not-so-cool kid commits too. I am not very cool, nor have I been for most of my life, but I think I could offer some nice improvements to the spw-web.

Please consider my request,

Michael

**Comment by seanpwhitehurst** [comment]
Hey Meek, 

U seem pretty cool. 

Sheen

**Comment by seanpwhitehurst** [comment]
I've decided to grant you access to the repo because u seem cool.
